default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ecom_development

test:
  <<: *default
  database: ecom_test

production:
  <<: *default
  database: ecom_production
  username: ecomerces
  password: <%= ENV['ECOM_DATABASE_PASSWORD'] %>
