regex:
  email: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
length:
  per_page_12: 12
  per_page_5: 5
admin:
  product_sorts: [["All", 1], ["Oldest", 2], ["Newest", 3], ["Price ASC", 4], ["Price DESC", 5]]
order:
  ASC: "ASC"
  DESC: "DESC"
  status: [["pending", 0], ["accept", 1], ["resolved", 2], ["rejected", 3]]
